package com.mirego.pilot.components.type

public enum class PilotTextContentType {
    NotSet,
    Name,
    NamePrefix,
    GivenName,
    MiddleName,
    FamilyName,
    NameSuffix,
    Nickname,
    JobTitle,
    OrganizationName,
    Location,
    FullStreetAddress,
    StreetAddressLine1,
    StreetAddressLine2,
    AddressCity,
    AddressState,
    AddressCityAndState,
    Sublocality,
    CountryName,
    PostalCode,
    TelephoneNumber,
    EmailAddress,
    URL,
    CreditCardNumber,
    Username,
    Password,
    NewPassword,
    OneTimeCode,
}
